name: Update BPB-Worker-Panel

on:
  schedule:
    - cron: '0 3 * * *' # 每天 UTC 时间 03:00
  workflow_dispatch: # 支持手动触发

permissions:
  contents: write  # ✅ 允许工作流提交更改

jobs:
  update-worker-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Get release info (choose Latest or Pre-release)
        id: get_release
        run: |
          # 👉 默认更新 Latest 版本
          api_url="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest"

          # ❌ 如果要改为更新 Pre-release，注释上一行并取消注释下一行：
          # api_url="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases"

          response=$(curl -s "$api_url")

          if echo "$api_url" | grep -q "/latest"; then
            version=$(echo "$response" | jq -r '.tag_name')
            asset_url=$(echo "$response" | jq -r '.assets[] | select(.name == "worker.js") | .browser_download_url')
          else
            version=$(echo "$response" | jq -r '[.[] | select(.prerelease == true)][0].tag_name')
            asset_url=$(echo "$response" | jq -r '[.[] | select(.prerelease == true)][0].assets[] | select(.name == "worker.js") | .browser_download_url')
          fi

          echo "asset_url=$asset_url" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Download and save as _worker.js
        run: |
          curl -L "${{ steps.get_release.outputs.asset_url }}" -o _worker.js

      - name: Check for changes or new file
        id: check_changes
        run: |
          if [ ! -f _worker.js ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if git ls-files --error-unmatch _worker.js > /dev/null 2>&1; then
            # 文件已被 Git 跟踪，检查是否有变更
            if git diff --quiet _worker.js; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          else
            # 文件是新增的
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          git commit -m "chore: update _worker.js to ${{ steps.get_release.outputs.version }}"
          git push
