name: Update BPB-Worker-Panel

on:
  schedule:
    - cron: '0 3 * * *' # 每天 UTC 时间 03:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-worker-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get release info (Latest or Pre-release)
        id: get_release
        run: |
          # 默认更新 Latest 版本
          api_url="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest"

          # 如需更新 Pre-release，注释上面一行，取消注释下一行：
          # api_url="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases"

          response=$(curl -s "$api_url")

          if echo "$api_url" | grep -q "/latest"; then
            version=$(echo "$response" | jq -r '.tag_name // empty')
            asset_url=$(echo "$response" | jq -r '.assets[]? | select(.name == "worker.js") | .browser_download_url // empty')
          else
            version=$(echo "$response" | jq -r '[.[] | select(.prerelease == true)] | first | .tag_name // empty')
            asset_url=$(echo "$response" | jq -r '[.[] | select(.prerelease == true)] | first | .assets[]? | select(.name == "worker.js") | .browser_download_url // empty')
          fi

          if [ -z "$version" ] || [ -z "$asset_url" ]; then
            echo "Error: Could not find version or asset URL for worker.js"
            exit 1
          fi

          echo "asset_url=$asset_url" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Download worker.js and add version header
        run: |
          curl -sL "${{ steps.get_release.outputs.asset_url }}" -o temp_worker.js
          echo "// Version: ${{ steps.get_release.outputs.version }}" > _worker.js
          cat temp_worker.js >> _worker.js
          rm temp_worker.js

      - name: Check for changes or new file
        id: check_changes
        run: |
          if [ ! -f _worker.js ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if git ls-files --error-unmatch _worker.js > /dev/null 2>&1; then
            if git diff --quiet _worker.js; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          git commit -m "chore: update _worker.js to ${{ steps.get_release.outputs.version }}"
          git push
